<?php

/**
 * @file
 * Defines core TS CK Entity Embed functionality.
 */

/**
 * Implements hook_hook_info().
 */
function ts_ck_entity_embed_hook_info() {
  $hooks = array(
    'ts_ck_entity_embed_entity_info' => array(
      'group' => 'ts_ck_entity_embed',
    ),
  );

  return $hooks;
}

/**
 * Implements hook_permission().
 */
function ts_ck_entity_embed_permission() {
  return array(
    'access ckeditor entity embed' => array(
      'title' => t('Access CKEditor Entity Embed plugin'),
    ),
  );
}

/**
 * Implements hook_ckeditor_plugin().
 */
function ts_ck_entity_embed_ckeditor_plugin() {
  $plugins = array();

  $plugins['entity'] = array(
    'name' => 'entity',
    'desc' => t('Plugin for embedding entities.'),
    'path' => drupal_get_path('module', 'ts_ck_entity_embed') . '/plugins/entity/',
    'buttons' => array(
      'Entity' => array(
        'icon' => 'icons/entity.png',
        'label' => 'Entity',
      ),
    ),
  );

  return $plugins;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ts_ck_entity_embed_form_alter(&$form, &$form_state, $form_id) {
  // TODO: Limit to forms with CKEditor enabled.

  // Attach embeddable entity info to form.
  $entity_info = ts_ck_entity_embed_get_entity_info();

  $attached_js = array(
    array(
      'data' => array(
        'ts_ck_entity_embed' => array('entity_info' => $entity_info),
      ),
      'type' => 'setting',
    ),
  );

  if (!isset($form['#attached'])) {
    $form['#attached'] = array();
  }

  if (!isset($form['#attached']['js'])) {
    $form['#attached']['js'] = array();
  }

  $form['#attached']['js'] += $attached_js;
}

/**
 * Implements hook_filter_info().
 */
function ts_ck_entity_embed_filter_info() {
  $filters['ckeditor_entity_embed'] = array(
    'title' => t('CKEditor Entity Embed'),
    'description' => t('Renders entities embedded into a text field.'),
    'process callback' => 'ts_ck_entity_embed_filter_process',
  );

  return $filters;
}

/**
 * Filter process callback for CKEditor Entity Embed plugin.
 */
function ts_ck_entity_embed_filter_process($text, $filter, $format, $langcode, $cache, $cache_id) {

}

/**
 * Gets embeddable entity information.
 *
 * @see hook_ts_ck_entity_embed_entity_info()
 */
function ts_ck_entity_embed_get_entity_info() {
  $entity_info = &drupal_static(__FUNCTION__);

  if (!isset($entity_info)) {
    $entity_info = array();

    foreach (module_implements('ts_ck_entity_embed_entity_info') as $module) {
      foreach (module_invoke($module, 'ts_ck_entity_embed_entity_info') as $entity_name => $info) {
        $entity_info[$entity_name] = $info;
      }
    }
  }

  return $entity_info;
}
